sonar.projectKey=rentlora_property-service
sonar.organization=rentlora
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.python.version=3.11
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/test_*.py
