name: ci
on:
  pull_request:
    branches: [main]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: write
  security-events: write
jobs:
  ci:
    uses: rentlora/.github/.github/workflows/ci-backend.yml@main
    with:
      service: property-service
    secrets: inherit
