name: release
on:
  release:
    types: [published]
concurrency: production-release-property-service
permissions:
  id-token: write
  contents: read
jobs:
  release:
    uses: rentlora/.github/.github/workflows/release.yml@main
    with:
      service: property-service
    secrets: inherit
